### ISSUE TITLE
Step Mode bug

### ISSUE THREAD

**Issue by IlluminaeX** [ImY0mu/hub-mobile-dist#1]
You can exit hard step mode by attacking with the guild PvP client

Edit: It's only temporary until you restart, it goes back to hard step mode after restarting

**Comment by ImY0mu** [comment]
Thank you for letting me know, I kinda overlooked the idea that someone will go for GPvP while doing the step mod. I'll fix it in the next update. 👍

**Comment by IlluminaeX** [comment]
Also, both step modes disable your keybinds if you exit step mode early (flag button or the bug)

**Comment by ImY0mu** [comment]
Should be fixed now, thanks again!
