### ISSUE TITLE
Can't zoom in

### ISSUE THREAD

**Issue by IlluminaeX** [ImY0mu/hub-mobile-dist#2]
Pressing `Ctrl -` zooms out, but doing `Ctrl +` doesn't zoom back in, and now it's stuck at this scale (help)

Edit: `Ctrl Shift +` does the job
![SimpleMMO_Hub_v2_akzeI4qGJk](https://user-images.githubusercontent.com/88865846/154824543-c1fc7585-34d5-4b73-b988-84212ee22674.png)

**Comment by ImY0mu** [comment]
I am unsure how you managed to do it. I am unable to reproduce it and those button presses do nothing. 😓
